### ISSUE TITLE
Slower linking time when using lld vs zld

### ISSUE THREAD

**Issue by adityadaniel** [keith/rules_apple_linker#17]
I currently implementing `zld` in our codebase and see significant reduce of linking time by 30% compared with `ld64`, and continuing our conversation on [Twitter](https://twitter.com/adityadaniel/status/1567765361315151873?s=20&t=nyYBwU1k-UAFomorpaF06g), I got slower linking time when using `lld` than `zld`

- `zld`: 25,3 secs (n=3)
- `lld`: 32,0 secs (n=3)

I tried to instrument the linking process as you suggest and attached is the profile file. Let me know if this the correct one since it's my first time use time profiler other than to profile iOS apps 😅 

[lld.trace.zip](https://github.com/keith/rules_apple_linker/files/9528275/lld.trace.zip)

Thank you in advance!

**Comment by keith** [comment]
It looks like the attached trace was only a 13s run, did you cancel it before it was done?

**Comment by adityadaniel** [comment]
No. The Instrument stop itself, but I also see the discrepancy where after the instrument stop, bazel still running and resulting around 30 secs in the build profile

**Comment by keith** [comment]
Nothing stands out in that trace as outliers to help debug much atm

**Comment by BertalanD** [comment]
Hey @adityadaniel!

I agree with keith that there's nothing immediately suspicious in the profile. A repro file would help in debugging this further. You can create one by passing `--reproduce repro.tar` to LLD. This will create a tarball named `repro.tar` which contains all inputs to the linker and the list of flags your build system passes to it.

**Comment by adityadaniel** [comment]
@keith @BertalanD thank you for looking into this, I'm gonna dig further into our project and will close this issue for now. Also, will try to reproduce it first using `--reproduce repro.tar`.
